apiVersion: v1
kind: PersistentVolume
metadata:
  name: gs-data-pv
spec:
  storageClassName: standard
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gs-data" # mounted on the minikube node