apiVersion: v1
kind: PersistentVolume
metadata:
  name: gs-settings-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gs-settings" # mounted on the minikube node