apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }

    http {
        default_type  application/octet-stream;

        #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        #                  '$status $body_bytes_sent "$http_referer" '
        #                  '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log  logs/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        #keepalive_timeout  0;
        keepalive_timeout  65;

        #gzip  on;

        #proxy setup
        proxy_cache_path    /var/cache/nginx/
                            levels=1:2
                            max_size=2g
                            inactive=60m
                            use_temp_path=off
                            keys_zone=tiles_cache:10m;
        server{
            listen 80;

            location ~* \.(?:manifest|appcache|html?|xml|json)$ {
                resolver 10.96.0.10;
                proxy_pass http://pg-tileserv:7800;  
                proxy_http_version 1.1; 
                proxy_set_header Upgrade $http_upgrade;  
                proxy_set_header Connection 'upgrade';  
                proxy_set_header Host $host;  
                proxy_cache_bypass $http_upgrade;  

            }
            location ~* \.(?:pbf)$ {
                resolver 10.96.0.10;
                proxy_pass http://pg-tileserv:7800;

                proxy_http_version 1.1;  
                
                proxy_set_header Upgrade $http_upgrade;  
                proxy_set_header Connection 'upgrade';  
                proxy_set_header Host $host;
                proxy_redirect off;  

                proxy_cache tiles_cache;
                proxy_cache_lock on;
                proxy_cache_revalidate on;

                proxy_cache_valid 200 204 302 1h;
                proxy_cache_valid 404 1m;

                proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;

                add_header X-Cache-Status $upstream_cache_status;
            }
                
        }

    }
