apiVersion: v1
kind: Service
metadata:
  name: geoserver-svc
spec:
  selector:
    app: geoserver # the service will expose all the pods that match this metadata <label>:<field>
  ports:
    - port: 8080 # how's exposed outside
      targetPort: 8080 # port of the container
  type: NodePort # makes the exposed pods accessible from outside the cluster