apiVersion: v1
kind: Service
metadata:
  name: pg-tileserv # the name that we find in the connection string
spec:
  selector:
    app: pg-tileserv
  ports:
    - port: 7800
      targetPort: 7800
# type: ClusterIp (the default one, the service is available only inside the k8s environment)